"""
Constants used across the UI layer of the LandEvolve application.
These centralize default values and magic strings to ensure consistency and maintainability.
"""

class SimulationDefaults:
    """
    Default simulation configuration values exposed in the UI setup screen.
    """
    # Default duration of a simulation run (e.g., number of years or cycles)
    PERIOD = 100
    
    # Default interval between calculations within the simulation
    TIME_STEP = 10


class ComponentDataKeys:
    """
    Dictionary keys used for passing around configured simulation components
    and their user-input parameters between UI forms and tables.
    """
    # Key mapping to the actual component object (e.g., FlowRouter)
    COMPONENT = "component"
    
    # Key mapping to the dictionary of parameters configured by the user for the component
    PARAMS = "params"


class SimulationParamKeys:
    """
    Dictionary keys used for assembling the final simulation configuration payload
    that is sent from the UI layer to the Engine/Simulation layer.
    """
    INPUT_TIFF_PATH = "input_tiff_path"
    SIMULATION_PERIOD = "simulation_period"
    TIME_STEP = "time_step"
    SIMULATION_NUMBER = "simulation_number"
    SELECTED_COMPONENTS = "selected_components"
    TRACK_FEATURE = "track_feature"
    FEATURE_SHAPEFILE = "feature_shapefile"
    FIRST_EFFECT_THRESHOLD = "first_effect_threshold"


class SimulationResultKeys:
    """
    Dictionary keys used in the raw output data generated by the Simulation Engine.
    """
    INITIAL_PLOT = "initial_plot"
    FINAL_PLOT = "final_plot"
    CHANGE_PLOT = "change_plot"
    GEOMORPHIC_CHANGE_PLOT = "geomorphic_change_plot"
    MASK_PLOT = "mask_plot"
    TIMELINE_HTML = "timeline_html"
    HYPSOMETRY_PLOT = "hypsometry_plot"
    FLUX_PLOT = "flux_plot"
    LONG_PROFILE_PLOT = "long_profile_plot"
    SLOPE_AREA_PLOT = "slope_area_plot"
    DRAINAGE_NETWORK_PLOT = "drainage_network_plot"
    SOIL_THICKNESS_PLOT = "soil_thickness_plot"
    CHANGE_EVENTS_PLOT = "change_events_plot"
    OUTPUT_DIR = "output_dir"
    GRID_SIZE = "grid_size"
    DIFF_MAX = "diff_max"
    TRACKER_CSV = "tracker_csv"
    TRACKER_PLOT = "tracker_plot"
    TRACKER_FIRST_EFFECT = "tracker_first_effect"
    DIAG_ABS_MAX_CHANGE = "diag_abs_max_change"
    DIAG_DEPOSITION_CELLS = "diag_deposition_cells"
    DIAG_EROSION_CELLS = "diag_erosion_cells"
    DIAG_MAX_DEPOSITION = "diag_max_deposition"
    DIAG_MAX_EROSION = "diag_max_erosion"
    DIAG_NET_CHANGE = "diag_net_change"
    DIAG_REGIME_LABEL = "diag_regime_label"


class SimulationStatsKeys:
    """
    Dictionary keys for passing performance statistics dynamically into the UI dialogs and logs.
    """
    TOTAL_TIME = "total_time"
    START_TIME = "start_time"
    PEAK_RAM = "peak_ram"
    FINAL_RAM = "final_ram"
    RAM_READINGS = "ram_readings"


class SimulationResultsWindowConsts:
    """
    Presentation strings (window titles, tab names, button texts) for the SimulationResultsWindow.
    """
    WINDOW_TITLE_PROGRESS = "Simulation Progress"
    WINDOW_TITLE_RESULTS = "Simulation Results"
    TAB_2D_VISUALIZATION = "2D Visualization"
    TAB_3D_VISUALIZATION = "3D Map"
    TAB_TIMELINE = "Sediment Timeline"
    TAB_ANALYSIS = "Analysis"
    TAB_FEATURE_TRACKING = "Feature Tracking"
    LBL_TIMELINE_NOT_AVAILABLE = "Sediment timeline not available for this simulation."
    LBL_ANALYSIS_NOT_AVAILABLE = "No analysis plots available for this simulation."
    BTN_SHOW_STATS = "Show Statistics"
    BTN_CLOSE = "Close"


class SimulationStatsDialogConsts:
    """
    Presentation strings for the SimulationStatsDialog.
    """
    WINDOW_TITLE = "Simulation Statistics"
    HEADER_TITLE = "Simulation Performance Statistics"
    GROUP_PERFORMANCE = "Performance Metrics"
    LBL_TOTAL_TIME = "<b>Total Time:</b>"
    LBL_START_TIME = "<b>Start Time:</b>"
    LBL_END_TIME = "<b>End Time:</b>"
    LBL_PEAK_RAM = "<b>Peak RAM Usage:</b>"
    LBL_FINAL_RAM = "<b>Final RAM Usage:</b>"
    LBL_AVERAGE_RAM = "<b>Average RAM:</b>"
    GROUP_DETAILS = "Detailed Information"
    BTN_CLOSE = "Close"
    VALUE_NA = "N/A"


class ProgressTrackerWidgetConsts:
    """
    Presentation strings for the ProgressTrackerWidget.
    """
    LBL_INIT = "Initializing Simulation..."
    LBL_STARTING_ENGINE = "Starting simulation engine..."
    PREFIX_TIME = "Time: "
    PREFIX_RAM = "RAM: "
    PREFIX_ERROR = "Error: "
    DEFAULT_TIME = "Time: 0:00:00"
    DEFAULT_RAM = "RAM: 0.0 MB"


class Carousel2DWidgetConsts:
    """
    Presentation strings for the Carousel2DWidget.
    """
    LBL_LOADING = "Loading..."
    LBL_NOT_FOUND = "Image not found: "
    BTN_INPUT = "Input Elevation"
    BTN_FINAL = "Final Elevation"
    BTN_DIFF = "Difference Map"
    LBL_SCALE_RANGE = "Scale Range (±m):"
    BTN_APPLY_SCALE = "Apply Scale"
    BTN_RESET_SCALE = "Reset to Auto"
    CHK_SYMLOG = "Enhance small changes (log)"
    CHK_REMOVE_UPLIFT = "Remove tectonic uplift"


class HomeWindowConsts:
    """
    Presentation strings and configuration constants for the HomeWindow.
    """
    IMG_ABOUT_FILENAME = "about.jpg"
    IMG_SCALED_WIDTH = 400
    IMG_SCALED_HEIGHT = 300
    LBL_TITLE_FALLBACK = "LandEvolve Visualization"
    LBL_IMG_UNAVAILABLE = "Image not available"


class DynamicFormConsts:
    """
    Strings and configuration keys for DynamicFormWidget.
    """
    OPTIONAL_TEXT = "Optional"
    BTN_BROWSE = "Browse..."
    FILE_DIALOG_TITLE = "Select Geology File"
    FILE_DIALOG_FILTER = "TIFF Files (*.tif *.tiff)"
    LITHOLOGY_HETEROGENEOUS = "Heterogeneous"
    
    # Conditional field keys
    FIELD_GEOLOGY_FILE = "geology_file"
    FIELD_K_SED = "K_sed"
    FIELD_K_BR = "K_br"
    FIELD_LITHOLOGY_TYPE = "lithology_type"

    # Precipitation mode-conditional fields
    FIELD_PRECIP_MODE = "mode"
    FIELD_PRECIPITATION = "precipitation"
    FIELD_PRECIP_RASTER = "precipitation_raster"
    FIELD_FINAL_PRECIPITATION = "final_precipitation"
    FIELD_VARIABILITY = "variability"
    FIELD_RANDOM_SEED = "random_seed"
    PRECIP_MODE_UNIFORM = "Uniform"
    PRECIP_MODE_SPATIAL = "Spatial"
    PRECIP_MODE_STOCHASTIC = "Stochastic"
    PRECIP_MODE_TREND = "Trend"

    # Tectonics mode-conditional fields
    FIELD_TECT_MODE = "mode"
    FIELD_UPLIFT_RATE = "uplift_rate"
    FIELD_UPLIFT_RASTER = "uplift_raster"
    TECT_MODE_UNIFORM = "Uniform"
    TECT_MODE_SPATIAL = "Spatial"


class ThreeDViewConsts:
    """
    Strings and configuration keys for ThreeDView.
    """
    LOG_FILE_NOT_FOUND = "3D plot file not found at: {}"
    LOG_GENERATION_FAILED = "Failed to generate 3D plot"
    FILE_HTML_COMPARISON = "view_3d_comparison.html"
    FILE_FALLBACK_TIFF = "final.tif"
    STR_ELEVATION_SUBSTRING = "elevation"
    EXT_TIFF = ".tif"


class AddComponentDlgConsts:
    """
    Strings and configuration keys for AddComponentDlg.
    """
    WINDOW_TITLE_EDIT = "Edit Component"
    BTN_UPDATE = "Update"
    LBL_NO_DESCRIPTION = "No description available."
    LBL_NO_COMPONENT = "No component selected."
