"""
Constants used across the UI layer of the LandEvolve application.
These centralize default values and magic strings to ensure consistency and maintainability.
"""

class SimulationDefaults:
    """
    Default simulation configuration values exposed in the UI setup screen.
    """
    # Default duration of a simulation run (e.g., number of years or cycles)
    PERIOD = 100
    
    # Default interval between calculations within the simulation
    TIME_STEP = 10


class LocationDataKeys:
    """
    String identifiers related to geographical location models.
    Used for safely retrieving dynamic attributes, such as relationships loaded via SQLAlchemy.
    """
    # Attribute name representing the list of geotiff files associated with a location
    GEOTIFFS = "geotiffs"


class ComponentDataKeys:
    """
    Dictionary keys used for passing around configured simulation components
    and their user-input parameters between UI forms and tables.
    """
    # Key mapping to the actual component object (e.g., FlowRouter)
    COMPONENT = "component"
    
    # Key mapping to the dictionary of parameters configured by the user for the component
    PARAMS = "params"


class SimulationParamKeys:
    """
    Dictionary keys used for assembling the final simulation configuration payload
    that is sent from the UI layer to the Engine/Simulation layer.
    """
    INPUT_TIFF_PATH = "input_tiff_path"
    SIMULATION_PERIOD = "simulation_period"
    TIME_STEP = "time_step"
    SIMULATION_NUMBER = "simulation_number"
    SELECTED_COMPONENTS = "selected_components"
    TRACK_FEATURE = "track_feature"
    FEATURE_SHAPEFILE = "feature_shapefile"


class SimulationResultKeys:
    """
    Dictionary keys used in the raw output data generated by the Simulation Engine.
    """
    INITIAL_PLOT = "initial_plot"
    FINAL_PLOT = "final_plot"
    CHANGE_PLOT = "change_plot"
    OUTPUT_DIR = "output_dir"
    GRID_SIZE = "grid_size"


class SimulationStatsKeys:
    """
    Dictionary keys for passing performance statistics dynamically into the UI dialogs and logs.
    """
    TOTAL_TIME = "total_time"
    START_TIME = "start_time"
    END_TIME = "end_time"
    PEAK_RAM = "peak_ram"
    FINAL_RAM = "final_ram"
    AVERAGE_RAM = "average_ram"
    RAM_READINGS = "ram_readings"
    DETAILED_INFO = "detailed_info"


class SimulationResultsWindowConsts:
    """
    Presentation strings (window titles, tab names, button texts) for the SimulationResultsWindow.
    """
    WINDOW_TITLE_PROGRESS = "Simulation Progress"
    WINDOW_TITLE_RESULTS = "Simulation Results"
    TAB_2D_VISUALIZATION = "2D Visualization"
    TAB_3D_VISUALIZATION = "3D Visualization"
    BTN_SHOW_STATS = "Show Stats"
    BTN_CLOSE = "Close"


class SimulationStatsDialogConsts:
    """
    Presentation strings for the SimulationStatsDialog.
    """
    WINDOW_TITLE = "Simulation Statistics"
    HEADER_TITLE = "Simulation Performance Statistics"
    GROUP_PERFORMANCE = "Performance Metrics"
    LBL_TOTAL_TIME = "<b>Total Time:</b>"
    LBL_START_TIME = "<b>Start Time:</b>"
    LBL_END_TIME = "<b>End Time:</b>"
    LBL_PEAK_RAM = "<b>Peak RAM Usage:</b>"
    LBL_FINAL_RAM = "<b>Final RAM Usage:</b>"
    LBL_AVERAGE_RAM = "<b>Average RAM:</b>"
    GROUP_DETAILS = "Detailed Information"
    BTN_CLOSE = "Close"
    VALUE_NA = "N/A"


class ProgressTrackerWidgetConsts:
    """
    Presentation strings for the ProgressTrackerWidget.
    """
    LBL_INIT = "Initializing Simulation..."
    LBL_STARTING_ENGINE = "Starting simulation engine..."
    PREFIX_TIME = "Time: "
    PREFIX_RAM = "RAM: "
    PREFIX_ERROR = "Error: "
    DEFAULT_TIME = "Time: 0:00:00"
    DEFAULT_RAM = "RAM: 0.0 MB"


class Carousel2DWidgetConsts:
    """
    Presentation strings for the Carousel2DWidget.
    """
    LBL_LOADING = "Loading..."
    LBL_NOT_FOUND = "Image not found: "
    BTN_INPUT = "Input Elevation"
    BTN_FINAL = "Final Elevation"
    BTN_DIFF = "Difference Map"
    LBL_SCALE_RANGE = "Scale Range (±m):"
    BTN_APPLY_SCALE = "Apply Scale"
    BTN_RESET_SCALE = "Reset to Auto"


class HomeWindowConsts:
    """
    Presentation strings and configuration constants for the HomeWindow.
    """
    IMG_ABOUT_FILENAME = "about.jpg"
    IMG_SCALED_WIDTH = 400
    IMG_SCALED_HEIGHT = 300
    LBL_TITLE_FALLBACK = "LandEvolve Visualization"
    LBL_IMG_UNAVAILABLE = "Image not available"


class DynamicFormConsts:
    """
    Strings and configuration keys for DynamicFormWidget.
    """
    OPTIONAL_TEXT = "Optional"
    BTN_BROWSE = "Browse..."
    FILE_DIALOG_TITLE = "Select Geology File"
    FILE_DIALOG_FILTER = "TIFF Files (*.tif *.tiff)"
    LITHOLOGY_HETEROGENEOUS = "Heterogeneous"
    
    # Conditional field keys
    FIELD_GEOLOGY_FILE = "geology_file"
    FIELD_K_SED = "K_sed"
    FIELD_K_BR = "K_br"
    FIELD_LITHOLOGY_TYPE = "lithology_type"


class ThreeDViewConsts:
    """
    Strings and configuration keys for ThreeDView.
    """
    LOG_FILE_NOT_FOUND = "3D plot file not found at: {}"
    LOG_GENERATION_FAILED = "Failed to generate 3D plot"
    FILE_HTML_COMPARISON = "view_3d_comparison.html"
    FILE_FALLBACK_TIFF = "final.tif"
    STR_ELEVATION_SUBSTRING = "elevation"
    EXT_TIFF = ".tif"


class AddComponentDlgConsts:
    """
    Strings and configuration keys for AddComponentDlg.
    """
    WINDOW_TITLE_EDIT = "Edit Component"
    BTN_UPDATE = "Update"
    LBL_NO_DESCRIPTION = "No description available."
    LBL_NO_COMPONENT = "No component selected."
